#!/usr/bin/env python
"""`just prod-env` — write a production-mode .env for a local deployed-shaped run.

    just prod-env                 -> .env.production-local
    just prod-env staging         -> SANAD_ENVIRONMENT=staging instead

`SANAD_ENVIRONMENT=production` makes `app.core.config._check_production_secrets`
refuse to start without four things: an RS256 keypair, an OTP pepper and an
invite secret that are not the `local-dev-` placeholders. That check is correct
and should not be softened — so this generates real values instead.

Two details this exists to get right, because both fail quietly by hand:

* **The PEM keys are multi-line.** A `.env` carries them only inside double
  quotes; unquoted, the reader stops at the first newline and pydantic receives
  a string that is a PEM header and nothing else. The failure surfaces later, as
  an unreadable key error at the first login.
* **It never overwrites.** Losing the keypair that signed the refresh tokens in
  a running local stack logs everyone out for no visible reason.

The output is gitignored (`.env.*` is, with `.env.example` and `.env.test` the
exceptions) and is a *local* production-shaped file. It is not how a real
deployment gets its secrets — that is a secrets manager, per docs/07.
"""

from __future__ import annotations

import secrets
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

REPO_ROOT = Path(__file__).resolve().parents[2]
TARGET = REPO_ROOT / ".env.production-local"

#: docs/08 §3 runs the API image against the same datastores; locally those are
#: the docker-compose ones on their offset host ports.
TEMPLATE = """# GENERATED by `just prod-env`. Local production-shaped configuration.
#
# Not a real deployment's secrets: a real one takes these from a secrets manager
# (docs/07 §4). This exists so you can run the stack the way it would run when
# deployed -- production settings, real datastores, /docs disabled -- on one
# machine.
#
# Gitignored. Do not commit. Do not reuse these keys anywhere real.

SANAD_ENVIRONMENT={environment}
SANAD_LOG_LEVEL=INFO
SANAD_SERVICE_NAME=sanad-api

SANAD_DATABASE_URL=postgresql+asyncpg://sanad:sanad@localhost:55432/sanad
SANAD_REDIS_URL=redis://localhost:56379/0

SANAD_S3_ENDPOINT_URL=http://localhost:59000
SANAD_S3_REGION=us-east-1
SANAD_S3_BUCKET=sanad-media
SANAD_S3_ACCESS_KEY_ID=sanadminio
SANAD_S3_SECRET_ACCESS_KEY=sanadminio-dev-secret

SANAD_CORS_ORIGINS=http://localhost:3000
NEXT_PUBLIC_API_BASE_URL=http://localhost:8000

# NullSms prints the OTP to the API log rather than sending it. That is the
# documented mode without an aggregator (SETUP.md §2) -- watch the `just up`
# stream for it, or the log file.
SANAD_SMS_PROVIDER=null

# --- secrets: generated, and required because SANAD_ENVIRONMENT is not local ---
SANAD_OTP_PEPPER={otp_pepper}
SANAD_INVITE_SECRET={invite_secret}

# Multi-line values MUST stay inside double quotes or the reader stops at the
# first newline.
SANAD_JWT_PRIVATE_KEY="{private_key}"
SANAD_JWT_PUBLIC_KEY="{public_key}"
"""


def generate_keypair() -> tuple[str, str]:
    """RS256, PKCS8 private and SubjectPublicKeyInfo public.

    Both formats are what `app.modules.identity.security` loads; 2048 bits is
    the floor for RS256 and there is no reason to go larger for a local run.
    """
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    private = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()
    public = (
        key.public_key()
        .public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        .decode()
    )
    return private.strip(), public.strip()


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    environment = argv[0] if argv else "production"
    if environment not in {"production", "staging", "ci", "local"}:
        print(f"unknown environment {environment!r}", file=sys.stderr)
        return 2

    if TARGET.exists():
        print(
            f"{TARGET.name} already exists — leaving it alone.\n"
            "  Delete it first if you want a new keypair. Regenerating one under a\n"
            "  running stack invalidates every refresh token already issued.",
            file=sys.stderr,
        )
        return 1

    private_key, public_key = generate_keypair()
    TARGET.write_text(
        TEMPLATE.format(
            environment=environment,
            otp_pepper=secrets.token_urlsafe(32),
            invite_secret=secrets.token_urlsafe(32),
            private_key=private_key,
            public_key=public_key,
        ),
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {TARGET.relative_to(REPO_ROOT)} (SANAD_ENVIRONMENT={environment})")
    print("  run it with:  just up-prod")
    if environment == "production":
        print("  note: /docs and /openapi.json are disabled when environment=production")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
